services:

  php:
    build: docker/php
    container_name: php-fpm
    tty: true
    volumes:
      - ./:/var/www/app
      - ./docker/php/z-overrides.ini:/usr/local/etc/php/conf.d/z-overrides.ini
    user: "${UID:-1000}:${GID:-1000}"
    depends_on:
      - db
    networks:
      - db-network
      - web-network
    env_file:
      .env

  nginx:
    image: nginx:1.27.5
    container_name: nginx
    tty: true
    volumes:
      - ./docker/nginx:/etc/nginx/conf.d
      - ./:/var/www/app
    ports:
      - "${NGINX_EXTERNAL_PORT:-3007}:80"
    depends_on:
      - php
    networks:
      - web-network
    env_file:
      .env

  db:
    image: mysql:8.1
    container_name: mysql
    restart: always
    environment:
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_USER: ${DB_USERNAME}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
    ports:
      - "${DB_EXTERNAL_PORT:-3308}:3306"
    volumes:
      - ./volumes/mysql:/var/lib/mysql
    networks:
      - db-network
    env_file:
      .env

  rabbitmq:
      image: rabbitmq:4.1
      container_name: rabbitmq
      ports:
        - "5672:5672"
        - "15672:15672"
      networks:
        - web-network
  
  redis:
    image: redis:8-alpine
    container_name: laravel-redis
    ports:
      - "6379:6379"
    networks:
      - web-network

networks:
  db-network:
    driver: bridge
  web-network:
    driver: bridge